# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                        Booster Settings                     #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# Database option that should be used.
# Options: "MYSQL" (separate server), "SQLITE" (local file).
database_option: "MYSQL"

database_host: "localhost"
database_port: "3306"
database_name: "boosters"
database_username: "veltus"
database_password: "5184"

bossbar_enabled: true
bossbar_color_minecraft: "GREEN"
bossbar_color_jobs: "YELLOW"
bossbar_color_mcmmo: "PURPLE"

actionbar_enabled: false

patch_experience_potions: false

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#               Do not change the following value!                #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
config_version: 1